#!/bin/bash

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=1
#SBATCH --mem=10G
#SBATCH --time=00:15:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli

set -e
set -x

# run the actual python code
singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py
